### ISSUE TITLE
Sharing HSM_Secret to XPRV tool

### ISSUE THREAD

**Issue by smolgrrr** [ElementsProject/cln-application#31]
Not an issue, but just thought you guys might want to see this recovery tool by an Umbrel user.
[https://community.umbrel.com/t/just-made-a-tool-to-recover-on-chain-hsm-secret-funds/14367/2](
https://community.umbrel.com/t/just-made-a-tool-to-recover-on-chain-hsm-secret-funds/14367/2
)

**Comment by ShahanaFarooqui** [comment]
@smolgrrr Thank you for the link. Added it as [discussion](https://github.com/ElementsProject/cln-application/discussions/32).

Closing this issue now.
