### ISSUE TITLE
If there sudden power off, core lightning is in starting mode after it is on. Won't start successfully

### ISSUE THREAD

**Issue by yshwanth** [ElementsProject/cln-application#33]

**Comment by ShahanaFarooqui** [comment]
@yshwanth Sorry but need more information to debug the issue.

**Comment by bitrequest** [comment]
Same issue

**Comment by bitrequest** [comment]
`Attaching to core-lightning_app_1, core-lightning_lightningd_1, core-lightning_c-lightning-rest_1, core-lightning_tor_1, core-lightning_tor_server_1, core-lightning_app_proxy_1
c-lightning-rest_1  |     at Socket.<anonymous> (/usr/src/app/lightning-client-js.js:80:23)
c-lightning-rest_1  |     at Socket.emit (node:events:513:28)
c-lightning-rest_1  |     at emitErrorNT (node:internal/streams/destroy:157:8)
c-lightning-rest_1  |     at emitErrorCloseNT (node:internal/streams/destroy:122:3)
c-lightning-rest_1  |     at processTicksAndRejections (node:internal/process/task_queues:83:21) {
c-lightning-rest_1  |   errno: -111,
c-lightning-rest_1  |   code: 'ECONNREFUSED',
c-lightning-rest_1  |   syscall: 'connect',
c-lightning-rest_1  |   address: '/root/.lightning/bitcoin/lightning-rpc'
c-lightning-rest_1  | }
app_1               | 2024/01/06 02:07:54 socat[782195] E connect(5, AF=1 "/root/.lightning/bitcoin/lightning-rpc", 40): Connection refused
app_1               | 
app_1               | Waiting for lightningd
app_1               | 2024/01/06 02:07:55 socat[782201] E connect(5, AF=1 "/root/.lightning/bitcoin/lightning-rpc", 40): Connection refused
app_1               | 
app_1               | Waiting for lightningd
app_1               | 2024/01/06 02:07:56 socat[782207] E connect(5, AF=1 "/root/.lightning/bitcoin/lightning-rpc", 40): Connection refused
app_1               | 
app_1               | Waiting for lightningd
app_1               | 2024/01/06 02:07:57 socat[782213] E connect(5, AF=1 "/root/.lightning/bitcoin/lightning-rpc", 40): Connection refused
app_proxy_1         | yarn run v1.22.19
app_proxy_1         | $ node ./bin/www
app_proxy_1         | [HPM] Proxy created: /  -> http://10.21.21.94:2103
app_proxy_1         | Waiting for 10.21.21.94:2103 to open...
tor_1               | Jan 05 18:45:38.000 [notice] While not bootstrapping, fetched this many bytes: 1984073 (consensus network-status fetch); 58540 (authority cert fetch); 13180211 (microdescriptor fetch)
tor_1               | Jan 05 19:01:58.000 [warn] Received http status code 404 ("Consensus not signed by sufficient number of requested authorities") from server 176.103.63.227:443 while fetching consensus directory.
tor_1               | Jan 05 19:06:58.000 [warn] Received http status code 404 ("Consensus not signed by sufficient number of requested authorities") from server 174.93.163.59:1234 while fetching consensus directory.
tor_1               | Jan 05 19:13:59.000 [warn] Received http status code 404 ("Consensus not signed by sufficient number of requested authorities") from server 174.93.163.59:1234 while fetching consensus directory.
tor_1               | Jan 05 19:19:43.000 [notice] No circuits are opened. Relaxed timeout for circuit 7698 (a Measuring circuit timeout 4-hop circuit in state doing handshakes with channel state open) to 60000ms. However, it appears the circuit has timed out anyway. [1 similar message(s) suppressed in last 18060 seconds]
tor_1               | Jan 06 00:45:38.000 [notice] Heartbeat: Tor's uptime is 9 days 12:00 hours, with 9 circuits open. I've sent 123.15 MB and received 143.25 MB. I've received 0 connections on IPv4 and 0 on IPv6. I've made 17 connections with IPv4 and 0 with IPv6.
tor_1               | Jan 06 00:45:38.000 [notice] While bootstrapping, fetched this many bytes: 693061 (consensus network-status fetch); 14102 (authority cert fetch); 12607058 (microdescriptor fetch)
tor_1               | Jan 06 00:45:38.000 [notice] While not bootstrapping, fetched this many bytes: 2043788 (consensus network-status fetch); 58540 (authority cert fetch); 13309768 (microdescriptor fetch)
lightningd_1        | Core-Lightning starting
lightningd_1        | 2023-12-27T12:47:05.527Z UNUSUAL plugin-clnrest.py: Killing plugin: timed out before replying to getmanifest
lightningd_1        | 2023-12-27T12:47:05.527Z **BROKEN** plugin-clnrest.py: Plugin marked as important, shutting down lightningd!
lightningd_1        | Can't recover from plugin failure, terminating.`

**Comment by bitrequest** [comment]
I think it has something to do with this:

`lightningd_1        | 2023-12-27T12:47:05.527Z UNUSUAL plugin-clnrest.py: Killing plugin: timed out before replying to getmanifest`

**Comment by ShahanaFarooqui** [comment]
Closing it for cln-appliation as it is the UX decision from core lightning [Issue 6924](https://github.com/ElementsProject/lightning/issues/6924)
