### ISSUE TITLE
listpeers no longer returns channel[] after 24.02, ChannelsCard blank

### ISSUE THREAD

**Issue by evansmj** [ElementsProject/cln-application#44]
The `listpeers` command no longer returns the channel[] array which is where the frontend is getting the channel information for the `ChannelsCard`.

The `listpeers.channels[]` array has been deprecated since 23.02 on March 14 2023.  
This means that the `ChannelsCard` displays no channels even though the node has channels.

Does cln-application need to add backwards compatibility, or can it just be updated to use another call?

**Comment by ShahanaFarooqui** [comment]
We try to keep the UI backwards compatibile.

**Comment by evansmj** [comment]
ok great i'm working on it, ill use isCompatibleVersion() to check for >= v23.02, if it is equal to or greater it should use `listpeerchannels` to get channels

**Comment by ShahanaFarooqui** [comment]
One year backwards compatibility already seems reasonable, so I wouldn’t worry too much about earlier versions. But if you still want to confirm, core lightning’s changelog is a good reference point to verify addition/deprecation of fields.

**Comment by evansmj** [comment]
https://github.com/ElementsProject/cln-application/pull/47

If one year is okay, I did it without supporting < 23.02 then.  At first I was writing it to support lower versions but it was becoming unwieldy and looked like it would be hard to maintain in the future.
