### ISSUE TITLE
isCompatibleVersion() doesn't work for release candidate versions

### ISSUE THREAD

**Issue by evansmj** [ElementsProject/cln-application#46]
It looks like `data-formatters.ts::isCompatibleVersion()` returns `false` with these arguments: 

(currentVersion: "v23.11rc1-464-g7cbff8a", checkVersion: "23.02").

It should return `true` since `23.11` is greater than `23.02`.

Tests should be written for this too, it could go under a new data-formatters.test.ts file.

```
import { isCompatibleVersion } from "./data-formatters";

describe("isCompatibleVersion", () => {

  test('Release Candidate versions', () => {
    expect(isCompatibleVersion("v23.11rc1-464-g7cbff8a", "23.02")).toBeTruthy();
    expect(isCompatibleVersion("v23.11rc1-464-g7cbff8a", "23.12")).toBeFalsy();
    expect(isCompatibleVersion("v24.02.1-modded", "23.02")).toBeTruthy();
  });
});
```

**Comment by ShahanaFarooqui** [comment]
Closing with PR #51.
