### ISSUE TITLE
Channel opening error

### ISSUE THREAD

**Issue by evansmj** [ElementsProject/cln-application#48]
After https://github.com/ElementsProject/cln-application/pull/47 is merged and the Channel card works again, channel opening doesn't display error messages.  It says data is undefined.

1. The error needs to be parsed, currently it says data is undefined.
2. If there is an app issue, that should be fixed as well.

**Comment by ShahanaFarooqui** [comment]
This error is not related to opening the channel. It was thrown by request Timeout. It is fixed with PR #47.

Now, either the channel will open or timeout error will be shown in the UI if the node is unable to open the channel in time.
