### ISSUE TITLE
Add to readme what stores this has been deployed to

### ISSUE THREAD

**Issue by evansmj** [ElementsProject/cln-application#58]
What platforms / stores has the cln-application been deployed to?  I heard its also on start9?  If there are others too we should update the readme with them.

**Comment by ShahanaFarooqui** [comment]
AFAIK, Start9 and Umbrel are the two stores hosting cln-application till now.

We already have Umbrel badge and opened an issue [#612](https://github.com/Start9Labs/documentation/issues/612) requesting Start9 to provide badge svgs to update their information.

**Comment by ShahanaFarooqui** [comment]
I added a temporary badge for Start9 with commit af7d0401f6d436fda4240d1b02688d54b382292a. I will update it whenever its official version is available. Closing the ticket now.
