### ISSUE TITLE
Updates for CLN v23.05 msat migration

### ISSUE THREAD

**Issue by ShahanaFarooqui** [ElementsProject/cln-application#6]
Update all screens and APIs to accommodate mSat migration implemented with CLN release v23.05.

**Comment by ShahanaFarooqui** [comment]
Closing with commit a81b615d79539a73890968ac9a2edaf7899547cc

**Comment by shyfire131** [comment]
FYI it seems as if the display value for the Bitcoin Wallet amount is off by a factor of 1000. That is, an actual on-chain balance of 100k sats shows up as 100M sats. 

The Lightning Wallet, channel balances all look correct now. 

This is running on commit d53e19548939641e7e12c756f43ef5fcf164225d

**Comment by ShahanaFarooqui** [comment]
> FYI it seems as if the display value for the Bitcoin Wallet amount is off by a factor of 1000. That is, an actual on-chain balance of 100k sats shows up as 100M sats.
 
Thank you for the quick testing and reporting. It has been fixed in next release branch `Release-0.0.4`, though it was enjoyable to see myself 1000 times richer :-p.
