### ISSUE TITLE
Open source license designation is missing from project

### ISSUE THREAD

**Issue by btcschellingpt** [ElementsProject/cln-application#64]
The designation of the open source license type appears to be missing from the project and should be added to provide certainty about the open source status and use by other projects etc.

Suggest MIT license per https://github.com/bitcoin/bitcoin?tab=MIT-1-ov-file#readme

**Comment by ShahanaFarooqui** [comment]
Thanks, fixed with commit 180e1415f2f729323c9d792df2368aee9d282168. Closing it now.
