### ISSUE TITLE
Version on umbrel says 24.05-modded

### ISSUE THREAD

**Issue by evansmj** [ElementsProject/cln-application#67]
Should the version when using the production umbrel cln app have "-modded"?

<img width="224" alt="Screenshot 2024-07-31 at 2 31 57 PM" src="https://github.com/user-attachments/assets/47a5a6d6-75fd-45a0-b897-c75a6cea5a75">

**Comment by ShahanaFarooqui** [comment]
Fixed with v24.08 Docker image.
