### ISSUE TITLE
cln-application 0.0.x - connectd: peer_out INVALID 22859

### ISSUE THREAD

**Issue by GTCLive** [ElementsProject/cln-application#76]
Hi. I've tried everything in my capacity to get around this and can't sort it myself and would be grateful for some guidance as to what to do next in order to id the bug and make the cln-application work.

I did so far:
- Reinstall the Debian os (tried Debian 10, 11, 12)
- Tried in several virtual machines, and on two different PC (real hardware)
- Tried 0.0.6 all the way down to 0.0.1
- Tried several lightningd releases, from the latest one, some older ones, including the master branch. 
-  Tried several npm/node version, -omit=dev, -audit fix, -force, everything. Has no change whatsoever. 

All in all, I've spent little over one week trying to make it work and regardless of what I try, I keep getting the lightningd.log filled with tens of thousand of errors and the CPU fluctuate between 0% to 100% every 2 or 3 seconds. 

Before I give up all hope in ever be able to using a lightning network, can one of the dev have a look and advise what/where I need to look in hope to have this functional please. That would be great. thanks

### Log Sample: 
`2024-11-11T05:26:41.273Z DEBUG   02a65e7dccf5bee5ddce99e09379fedd27572d0f97ac18053b0035e10545f4f53c-connectd: peer_out INVALID 22859`
`2024-11-11T05:26:41.275Z DEBUG   02a65e7dccf5bee5ddce99e09379fedd27572d0f97ac18053b0035e10545f4f53c-connectd: peer_out INVALID 22859`
`2024-11-11T05:26:41.278Z DEBUG   02a65e7dccf5bee5ddce99e09379fedd27572d0f97ac18053b0035e10545f4f53c-connectd: peer_out INVALID 22859`
`2024-11-11T05:26:41.281Z DEBUG   02a65e7dccf5bee5ddce99e09379fedd27572d0f97ac18053b0035e10545f4f53c-connectd: peer_out INVALID 22859`
`2024-11-11T05:26:41.284Z DEBUG   02a65e7dccf5bee5ddce99e09379fedd27572d0f97ac18053b0035e10545f4f53c-connectd: peer_out INVALID 22859`

x10k x20k x30k... it's endlessly spamming the log like above...

**Comment by GTCLive** [comment]
This also occasionally shows up. Not idea if it's relevant neither know what it means. Anyone seen this before?

Thank you. 

`Nov 11 01:11:30 debian-asus npm[633616]: > node ./dist/server.js`
`Nov 11 01:11:32 debian-asus npm[633628]: {"level":"warn","message":"\tServer running at http://192.168.10.137:2103","timestamp":"2024-11-11 01:11:32:1132"}`
`Nov 11 01:11:42 debian-asus npm[633628]: {"level":"error","message":"\tServer error: ForbiddenError: invalid csrf token","timestamp":"2024-11-11 01:11:42:1142"}`
`Nov 11 01:11:42 debian-asus npm[633628]: {"level":"error","message":"\tInvalid CSRF token. Form tempered.","timestamp":"2024-11-11 01:11:42:1142"}`

**Comment by ShahanaFarooqui** [comment]
@GTCLive Opened an issue on core lightning's repository at https://github.com/ElementsProject/lightning/issues/7802.

Closing it here as no further action is required by cln-application.

**Comment by GTCLive** [comment]
Oh nooo :( Shahana, please tell me _"no further action is required by cln-application."_ does not mean that this awesome app is retired? It's awesome, it works, just a nasty annoying bug (for me anyway) that fills the log and ramp the CPU up/down.

**Comment by ShahanaFarooqui** [comment]
> Oh nooo :( Shahana, please tell me _"no further action is required by cln-application."_ does not mean that this awesome app is retired? It's awesome, it works, just a nasty annoying bug (for me anyway) that fills the log and ramp the CPU up/down. 

The CLN-application is being maintained and developed regularly. But your issue is related to core lightning NOT cln-application. It cannot be fixed by cln-application, so I closed this issue and opened another on core lightning's repo.

**Comment by GTCLive** [comment]
Ah snap, I didn't know it was lightningd. 

I'm eager to learn, I desperately need a front-end to CLN (neither can get any wallets working, reliably anyway). I really just need to know where to start looking for that bug to save myself 3 months (lol) and who knows I might be able to sort it out myself (I'm a dreamer as you can see!).

Anyway. Let's hope a dev is already aware of knows how to patch this up. My last stab at LN, wish me luck :/

Thanks for putting me in the correct direction btw. Super kind x
